### ISSUE TITLE
Master Issue to track work on CI

### ISSUE THREAD

**Issue by laughinghan** [mathquill/mathquill#649]
- [x] run our unit tests on Sauce Labs via CircleCI: #625 
- [x] collect screenshots of our visual tests: #636 
- [x] collect visual diffs of those screenshots against the last build run: #645

**Comment by laughinghan** [comment]
so the next steps I'm imagining would all be towards the goal of posting something useful as a GitHub comment, which I think will make an outsize difference in the utility of this awesome CI screenshot work.

Ideas:
- can we crop the diffs to be just the areas that are different, with a little bit of padding?
- obviously, stabilizing them so that spurious diffs are avoided would be nice
    + is the current measure of difference just the number of pixels different? Any way to also account for how actually different the pixels are (so that e.g. gray and slightly darker gray count for only a little)
- can we reduce the screen width to 6.5 CSS inches (624 pixels) so that more of 'em could fit side-by-side?

**Comment by laughinghan** [comment]
More issues worth noting:
- [ ] currently visual diff is against latest build, which will compare between unrelated PRs, want against master and against last build of the same PR
- [ ] currently if screenshotting fails, the next build will fails since it can't get screenshots from it. This is easy to workaround (just rebuild), but the Right Thing would be to walk backwards seeking the last good build that does have screenshots

**Comment by laughinghan** [comment]
> is the current measure of difference just the number of pixels different?

Yes, we use `AE`, which is the "absolute count of pixels that are different", with no `-fuzz` factor:

http://www.imagemagick.org/script/command-line-options.php#metric

Other promising ones are available, such as "FUZZ: mean color distance".

**Comment by laughinghan** [comment]
#645 has made CI rather unstable, I've now seen 3 different branches where it'll say:
> compare.im6: image widths or heights differ `PREV_PINNED_Windows_7_Internet_Explorer.png' @ error/compare.c/CompareImageCommand/962.

Or:
> curl: try 'curl --help' or 'curl --manual' for more information
compare.im6: unable to open image `PREV_PINNED_Windows_7_Internet_Explorer.png': No such file or directory @ error/blob.c/OpenBlob/2641.

On rebuilding it then works of course, since it's comparing against screenshots from the failed build which was the same commit.

Branches I've seen this happen:
- `docs.bump-jquery`: [build 205](https://circleci.com/gh/mathquill/mathquill/205), [build 206](https://circleci.com/gh/mathquill/mathquill/206)
- `build.release-process`: [build 210](https://circleci.com/gh/mathquill/mathquill/210), [build 216](https://circleci.com/gh/mathquill/mathquill/216)
- `feature.diacritics`: [build 221](https://circleci.com/gh/mathquill/mathquill/221)

So, things we should probably do about this:
- [ ] failure to generate visual diffs should not count as test failure (should failure to capture screenshots even count as test failure?)
- [ ] our visual diffs need to handle screenshots of different height. Hell, the most common scenario where the screenshots matter is where we fix a visual bug or add a new command and add a corresponding visual test, which increases the height of the screenshot.
    + Idea for a visual diff algorithm specific to screenshots of webpages:
       ![visual diffs of screenshots of webpages](https://cloud.githubusercontent.com/assets/225809/16325125/f978129a-396f-11e6-899d-afb2855f0ae0.jpeg)
        - expect same width, but possibly different height
        - for screenshots A and B, assume WLOG B taller than A
        - crop B to same height as A with top edges lined up and with bottom edges lined up, call them B-upper and B-lower
        - use ImageMagick to diff A against each of B-upper and B-lower
        - map each diff back onto B and take their intersection
- [x] also, the todo list item already mentioned above:

    > walk backwards seeking the last good build that does have screenshots

**Comment by laughinghan** [comment]
One problem that comes to mind with that variable-height visual diff idea is if the diffs of A against both B-upper and B-lower are empty, for example, a page with 5 lines that all just say the word "Text", and a page with 6 such lines; the algorithm would diff the 5 lines against the top 5 lines and bottom 5 lines of the latter, and find no differences at all. Other than this pathological case, are there any other possible ways the combined diff as calculated by the algorithm is shorter than the height difference between A and B? Or is it the case that if there is a difference at all, it's guaranteed to fully account for how much taller B is than A? What about blank background space, that's kinda like repeating lines right?

**Comment by laughinghan** [comment]
> Or is it the case that if there is a difference at all, it's guaranteed to fully account for how much taller B is than A?

Nonsense. Consider:

```
1
3
```
 
vs

```
1
2
3
```

The line containing `2` may be like, 36px, but if the glyph of `2` itself is like 30px, that's how big the diff returned by the above algorithm will be; the lines of blank pixels above and below the `2` that were inserted won't be noticed at all.

However, if instead of the intersection of the upper and lower diffs, we consider the union, then (I believe) any row of pixels that _isn't_ in the union (that is, any row of pixels that is the same in _all_ of screenshots A, B-upper, _and_ B-lower) could be inserted into screenshot A to produce B. Yes, that's ambiguous, but that's the point: in the example of 5 vs 6 lines that each say "Text", you could insert a line saying "Text" between any two lines in the image of 5 lines (or at the top or bottom) and they would all produce the 6 lines.

So in that case, I propose we take the height of screenshot B, subtract the height of screenshot A, and subtract the height of the diff from the above algorithm (using the intersection) to get N, the number of extra rows of pixels not accounted for by the diff from the above aglorithm; then, starting from the lowest pixel in the diff from the intersection algorithm, find the highest rows of pixels that satisfy this criterion (not in union of upper and lower diffs i.e. same across A, B-upper, and B-lower), and highlight N of them. That should result in something like (pretend the middle and right rectangles are the same size, obviously):

![visual diff](https://cloud.githubusercontent.com/assets/225809/22910600/e29679d2-f20f-11e6-941d-aeea51efa467.JPG)

Hmm, maybe these "added rows of pixels that are the same as existing rows in A" should be a lighter highlight color? Should we also highlight some rows from the intersection diff this lighter color too, so you can distinguish which rows of pixels were inserted vs modified?
